name: path_parsing
version: 0.1.4
description: >
  A Dart library to help with SVG Path parsing and code generation.  Used by Flutter SVG.
author: Dan Field <dfield@gmail.com>
homepage: https://github.com/dnfield/dart_path_parsing

dependencies:
  vector_math: ">=2.0.6 <3.0.0" # google - https://github.com/google/vector_math.dart
  meta: ">=1.1.2 <2.0.0" # dart.dev

dev_dependencies:
  path: ^1.5.1 # dart.dev
  test: ^1.3.4 # dart.dev

environment:
  sdk: ">=1.19.0 <3.0.0"
