name: path_parsing
version: 0.1.2
description: >
  A Dart library to help with SVG Path parsing and code generation
author: Dan Field <dfield@gmail.com>
homepage: https://github.com/dnfield/dart_path_parsing

dependencies:
  build: ^0.12.7
  meta: ">=1.1.2 <2.0.0"
  source_gen: ^0.9.0
  vector_math: ">=2.0.6 <3.0.0"

dev_dependencies:
  build_config: ^0.3.1
  build_runner: ^0.9.2
  build_test: ^0.10.3
  code_builder: any
  path: ^1.5.1
  test: ">=0.12.34 <1.0.0"

environment:
  sdk: ">=2.0.0-dev <3.0.0"